"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";

type Category = { id: string; name: string };
const goals = ["Build foundational Islamic knowledge", "Improve Qur'an understanding", "Study Hadith", "Study Fiqh", "Learn at my own pace", "Follow structured learning", "Prepare for advanced study"];

export default function OnboardingPage() {
  const { status } = useSession(); const router = useRouter();
  const [step, setStep] = useState(1); const [categories, setCategories] = useState<Category[]>([]); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ accountIntention: "LEARN", preferredLanguage: "en", preferredDifficulty: "BEGINNER", categoryIds: [] as string[], goals: [] as string[] });
  useEffect(() => { if (status === "unauthenticated") router.replace("/login?callbackUrl=/onboarding"); fetch("/api/categories").then(r => r.json()).then(d => setCategories(d.data ?? [])).catch(() => {}); }, [status, router]);
  const toggle = (key: "categoryIds" | "goals", value: string) => setForm(f => ({ ...f, [key]: f[key].includes(value) ? f[key].filter(x => x !== value) : [...f[key], value] }));
  const save = async (complete: boolean) => { setSaving(true); try { const r = await fetch("/api/learner-profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, onboardingStep: complete ? 3 : step, onboardingCompleted: complete }) }); const d = await r.json(); if (!d.success) throw new Error(d.error); router.push(form.accountIntention === "TEACH" ? "/scholar-application" : "/dashboard"); } finally { setSaving(false); } };
  if (status === "loading") return null;
  return <main className="max-w-2xl mx-auto px-4 py-12"><p className="text-xs text-[var(--accent)] uppercase tracking-widest">Welcome to ILM · Step {step} of 3</p><div className="h-1.5 bg-[var(--border)] rounded-full mt-3 mb-8"><div className="h-full bg-[var(--accent)] rounded-full" style={{ width: `${step * 33}%` }} /></div>
    {step === 1 && <section className="glass-card rounded-2xl p-6 space-y-5"><h1 className="font-display text-2xl font-bold">How will you use ILM?</h1><p className="text-sm text-[var(--text-muted)]">Choosing teaching starts an application; it does not grant instructor access.</p>{[ ["LEARN", "I want to learn"], ["TEACH", "I want to teach"]].map(([value, label]) => <label key={value} className="flex gap-3 p-4 border border-[var(--border)] rounded-xl cursor-pointer"><input type="radio" checked={form.accountIntention === value} onChange={() => setForm({ ...form, accountIntention: value })} />{label}</label>)}<button className="btn-primary" onClick={() => setStep(2)}>Continue</button></section>}
    {step === 2 && <section className="glass-card rounded-2xl p-6 space-y-5"><h1 className="font-display text-2xl font-bold">What would you like to study?</h1><div className="flex flex-wrap gap-2">{categories.map(c => <button type="button" key={c.id} onClick={() => toggle("categoryIds", c.id)} className={`px-3 py-2 rounded-lg text-sm border ${form.categoryIds.includes(c.id) ? "bg-[var(--accent)] text-white" : "border-[var(--border)]"}`}>{c.name}</button>)}</div><div className="flex justify-between"><button className="btn-secondary" onClick={() => setStep(1)}>Back</button><button className="btn-primary" onClick={() => setStep(3)}>Continue</button></div></section>}
    {step === 3 && <section className="glass-card rounded-2xl p-6 space-y-5"><h1 className="font-display text-2xl font-bold">Set your learning preferences</h1><select className="input-themed" value={form.preferredLanguage} onChange={e => setForm({ ...form, preferredLanguage: e.target.value })}><option value="en">English</option><option value="ar">Arabic</option><option value="ur">Urdu</option></select><select className="input-themed" value={form.preferredDifficulty} onChange={e => setForm({ ...form, preferredDifficulty: e.target.value })}><option value="BEGINNER">Beginner</option><option value="INTERMEDIATE">Intermediate</option><option value="ADVANCED">Advanced</option></select><div className="flex flex-wrap gap-2">{goals.map(g => <button type="button" key={g} onClick={() => toggle("goals", g)} className={`px-3 py-2 rounded-lg text-sm border ${form.goals.includes(g) ? "bg-[var(--accent)] text-white" : "border-[var(--border)]"}`}>{g}</button>)}</div><div className="flex justify-between"><button className="btn-secondary" onClick={() => setStep(2)}>Back</button><button className="btn-primary" disabled={saving} onClick={() => void save(true)}>{saving ? "Saving…" : form.accountIntention === "TEACH" ? "Continue to application" : "Finish"}</button></div></section>}</main>;
}
