"use client";
import { useEffect, useState } from "react";
type Item = { id: string; status: string; submittedAt: string | null; specializations: string[]; user: { name: string; email: string; country: string | null }; decisionReason?: string | null };
export default function ScholarApplicationsPage() {
  const [items, setItems] = useState<Item[]>([]); const [status, setStatus] = useState(""); const [q, setQ] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const load = async () => { setLoading(true); const r = await fetch(`/api/admin/scholar-applications?status=${encodeURIComponent(status)}&q=${encodeURIComponent(q)}`); const d = await r.json(); if (d.success) setItems(d.data.items); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const review = async (id: string, action: "UNDER_REVIEW" | "APPROVE" | "REJECT") => { const decisionReason = action === "REJECT" ? window.prompt("Applicant-visible reason for rejection:") : ""; if (action === "REJECT" && !decisionReason) return; const r = await fetch(`/api/admin/scholar-applications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, decisionReason }) }); const d = await r.json(); setMessage(d.success ? "Application updated." : d.error || "Unable to update application"); if (d.success) void load(); };
  return <div className="p-6 sm:p-10"><h1 className="font-display text-3xl font-bold">Scholar Applications</h1><p className="text-sm text-[var(--text-muted)] mt-1">Private applications. Documents are intentionally not exposed here without an authorized private-file delivery system.</p><div className="flex gap-3 mt-6"><input className="input-themed" placeholder="Search name or email" value={q} onChange={e => setQ(e.target.value)} /><select className="input-themed max-w-48" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{["DRAFT","SUBMITTED","UNDER_REVIEW","APPROVED","REJECTED"].map(x => <option key={x}>{x}</option>)}</select><button className="btn-primary" onClick={() => void load()}>Filter</button></div>{message && <p className="mt-3 text-sm">{message}</p>}<div className="mt-6 space-y-3">{loading ? <p>Loading…</p> : items.map(item => <article key={item.id} className="border border-[var(--border)] rounded-xl p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{item.user.name}</h2><p className="text-sm text-[var(--text-muted)]">{item.user.email} · {item.user.country || "Country not provided"}</p><p className="text-sm mt-2">{item.specializations.join(", ")}</p></div><strong className="text-sm">{item.status.replaceAll("_", " ")}</strong></div>{["SUBMITTED", "UNDER_REVIEW"].includes(item.status) && <div className="flex gap-2 mt-4"><button className="btn-secondary text-sm" onClick={() => void review(item.id, "UNDER_REVIEW")}>Review</button><button className="btn-primary text-sm" onClick={() => void review(item.id, "APPROVE")}>Approve</button><button className="text-sm px-3 py-2 rounded-lg border border-red-500/30 text-red-400" onClick={() => void review(item.id, "REJECT")}>Reject</button></div>}</article>)}</div></div>;
}
