"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";

const empty = { bio: "", city: "", education: "", institutions: [] as string[], qualifications: [] as string[], specializations: [] as string[], teachingExperience: "", teachingYears: null as number | null, intendedCategories: [] as string[], teachingLanguages: ["English"] as string[], documentKeys: [] as string[] };
export default function ScholarApplicationPage() {
  const { status } = useSession(); const router = useRouter(); const [form, setForm] = useState(empty); const [state, setState] = useState<string>("DRAFT"); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (status === "unauthenticated") router.replace("/login?callbackUrl=/scholar-application"); fetch("/api/scholar-applications").then(r => r.json()).then(d => { if (d.data) { setForm({ ...empty, ...d.data }); setState(d.data.status); } }).catch(() => {}); }, [status, router]);
  const submit = async (submitNow: boolean) => { setSaving(true); setMessage(""); try { const r = await fetch("/api/scholar-applications", { method: submitNow ? "POST" : "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const d = await r.json(); if (!d.success) throw new Error(d.error || "Unable to save application"); setState(d.data.status); setMessage(submitNow ? "Application submitted for admin review." : "Draft saved."); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save application"); } finally { setSaving(false); } };
  const updateList = (key: "specializations" | "qualifications" | "institutions" | "intendedCategories" | "teachingLanguages", value: string) => setForm(f => ({ ...f, [key]: value.split(",").map(x => x.trim()).filter(Boolean) }));
  if (status === "loading") return null;
  const locked = ["SUBMITTED", "UNDER_REVIEW", "APPROVED"].includes(state);
  return <main className="max-w-2xl mx-auto px-4 py-12"><p className="text-xs text-[var(--accent)] uppercase tracking-widest">Instructor pathway</p><h1 className="font-display text-3xl font-bold mt-2">Become a Scholar / Instructor</h1><p className="text-[var(--text-muted)] mt-2">Submit your qualifications for a private admin review. Approval is required before instructor access is granted.</p>{message && <p className="mt-4 p-3 rounded-xl bg-[var(--accent-dim)] text-sm">{message}</p>}
    <div className="glass-card rounded-2xl p-6 mt-6 space-y-4"><label className="block text-sm">Bio<textarea disabled={locked} value={form.bio} onChange={e => setForm({ ...form, bio: e.target.value })} className="input-themed mt-1 min-h-28" minLength={30} /></label><label className="block text-sm">City<input disabled={locked} value={form.city} onChange={e => setForm({ ...form, city: e.target.value })} className="input-themed mt-1" /></label><label className="block text-sm">Religious / academic background<textarea disabled={locked} value={form.education} onChange={e => setForm({ ...form, education: e.target.value })} className="input-themed mt-1 min-h-24" /></label>
      <label className="block text-sm">Institutions studied at (comma separated)<input disabled={locked} value={form.institutions.join(", ")} onChange={e => updateList("institutions", e.target.value)} className="input-themed mt-1" /></label><label className="block text-sm">Qualifications (comma separated)<input disabled={locked} value={form.qualifications.join(", ")} onChange={e => updateList("qualifications", e.target.value)} className="input-themed mt-1" /></label><label className="block text-sm">Areas of specialization<input required disabled={locked} value={form.specializations.join(", ")} onChange={e => updateList("specializations", e.target.value)} className="input-themed mt-1" /></label><label className="block text-sm">Teaching experience<textarea disabled={locked} value={form.teachingExperience} onChange={e => setForm({ ...form, teachingExperience: e.target.value })} className="input-themed mt-1" /></label><label className="block text-sm">Years teaching<input disabled={locked} type="number" min="0" value={form.teachingYears ?? ""} onChange={e => setForm({ ...form, teachingYears: e.target.value ? Number(e.target.value) : null })} className="input-themed mt-1" /></label><label className="block text-sm">Subjects you plan to teach<input required disabled={locked} value={form.intendedCategories.join(", ")} onChange={e => updateList("intendedCategories", e.target.value)} className="input-themed mt-1" /></label><label className="block text-sm">Teaching languages<input required disabled={locked} value={form.teachingLanguages.join(", ")} onChange={e => updateList("teachingLanguages", e.target.value)} className="input-themed mt-1" /></label>
      {!locked && <div className="flex gap-3 pt-2"><button className="btn-secondary" disabled={saving} onClick={() => void submit(false)}>Save draft</button><button className="btn-primary" disabled={saving} onClick={() => void submit(true)}>{saving ? "Saving…" : "Submit application"}</button></div>}{locked && <p className="text-sm text-[var(--text-muted)]">Status: <strong>{state.replaceAll("_", " ")}</strong></p>}</div></main>;
}
